#!/usr/bin/env python3
"""Validate lncRNA-classifier leaderboard submissions and (re)build LEADERBOARD.md.

A submission is a directory under results/<challenge>/leaderboard/submissions/<name>/
containing:
  predictions.csv   target, cell_line, y_pred_proba for every held-out test row
                     (exactly the format lncfit.pipeline.LncRnaPipeline writes to
                     a run's predictions.csv -- just copy that file over)
  submission.yaml    {submitter: "...", model: "...", description: "..." (optional)}

AUROC/AUPRC are recomputed here directly from predictions.csv against the real
held-out labels in the test set -- a submitted metrics.csv or y_true column is
never trusted for scoring, only target/cell_line/y_pred_proba are read.

Usage:
  python scripts/build_leaderboard.py --challenge lncrna_rra_day14

Exits non-zero (after still writing LEADERBOARD.md for whatever validated) if
any submission is malformed, missing, or doesn't cover the held-out test set
exactly -- so CI can fail the check without silently dropping a bad entry.
"""
import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).parent.parent))

from lncfit.screen_data import LncRnaRecord, load_jsonl
from lncfit.xgboost_model import evaluate_lncrna_by_group

_DEFAULT_TEST_PATH = "data/processed/test_lncrna_day14_chrom1.jsonl.gz"
_REQUIRED_PRED_COLS = {"target", "cell_line", "y_pred_proba"}
_REQUIRED_SUBMISSION_FIELDS = {"submitter", "model"}


class SubmissionError(Exception):
    pass


def _load_truth(test_path: str):
    records = load_jsonl(test_path, record_cls=LncRnaRecord)
    truth = {(r.target, r.cell_line): r.label for r in records}
    return records, truth


def _score_submission(sub_dir: Path, records: list, truth: dict) -> dict:
    submission_yaml = sub_dir / "submission.yaml"
    predictions_csv = sub_dir / "predictions.csv"

    if not submission_yaml.exists():
        raise SubmissionError(f"{sub_dir.name}: missing submission.yaml")
    if not predictions_csv.exists():
        raise SubmissionError(f"{sub_dir.name}: missing predictions.csv")

    with open(submission_yaml) as fh:
        meta = yaml.safe_load(fh) or {}
    missing_fields = _REQUIRED_SUBMISSION_FIELDS - meta.keys()
    if missing_fields:
        raise SubmissionError(
            f"{sub_dir.name}: submission.yaml missing field(s): {sorted(missing_fields)}"
        )

    preds = pd.read_csv(predictions_csv)
    missing_cols = _REQUIRED_PRED_COLS - set(preds.columns)
    if missing_cols:
        raise SubmissionError(
            f"{sub_dir.name}: predictions.csv missing column(s): {sorted(missing_cols)}"
        )

    if preds.duplicated(subset=["target", "cell_line"]).any():
        raise SubmissionError(f"{sub_dir.name}: predictions.csv has duplicate (target, cell_line) rows")

    pred_keys = set(zip(preds["target"], preds["cell_line"]))
    truth_keys = set(truth.keys())
    missing_rows = truth_keys - pred_keys
    extra_rows = pred_keys - truth_keys
    if missing_rows:
        raise SubmissionError(
            f"{sub_dir.name}: predictions.csv is missing {len(missing_rows)} row(s) "
            "required by the held-out test set"
        )
    if extra_rows:
        raise SubmissionError(
            f"{sub_dir.name}: predictions.csv has {len(extra_rows)} row(s) not in the "
            "held-out test set"
        )

    pred_lookup = {(row.target, row.cell_line): row.y_pred_proba for row in preds.itertuples()}
    y_true = [truth[(r.target, r.cell_line)] for r in records]
    y_pred_proba = [pred_lookup[(r.target, r.cell_line)] for r in records]

    metrics_rows = evaluate_lncrna_by_group(records, y_true, y_pred_proba)
    overall = next(r for r in metrics_rows if r["split"] == "Overall")

    return {
        "name": sub_dir.name,
        "submitter": str(meta["submitter"]),
        "model": str(meta["model"]),
        "description": str(meta.get("description", "")),
        "auroc": overall["auroc"],
        "auprc": overall["auprc"],
    }


def _render_leaderboard(challenge: str, rows: list[dict], n_errors: int) -> str:
    lines = [
        f"# Leaderboard -- {challenge}",
        "",
        "Auto-generated by `scripts/build_leaderboard.py` (via CI) -- do not edit by hand.",
        "AUROC/AUPRC are recomputed directly from each submission's `predictions.csv` "
        "against the real held-out test labels, not read from any submitted metrics file.",
        "",
        "| Rank | Submitter | Model | AUPRC | AUROC | Submission |",
        "|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(rows, 1):
        lines.append(
            f"| {i} | {r['submitter']} | {r['model']} | {r['auprc']:.4f} | {r['auroc']:.4f} | "
            f"[{r['name']}](submissions/{r['name']}/) |"
        )
    if n_errors:
        lines += ["", f"{n_errors} submission(s) failed validation and are not scored above -- see CI log."]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--challenge", default="lncrna_rra_day14", help="results/<challenge>/leaderboard/...")
    parser.add_argument("--test-path", default=_DEFAULT_TEST_PATH, help="Held-out labeled test set.")
    args = parser.parse_args()

    challenge_dir = Path("results") / args.challenge / "leaderboard"
    submissions_dir = challenge_dir / "submissions"
    leaderboard_path = challenge_dir / "LEADERBOARD.md"

    if not submissions_dir.exists():
        sys.exit(f"No submissions directory found at {submissions_dir}")

    records, truth = _load_truth(args.test_path)

    rows = []
    errors = []
    for sub_dir in sorted(submissions_dir.iterdir()):
        if not sub_dir.is_dir():
            continue
        try:
            rows.append(_score_submission(sub_dir, records, truth))
        except SubmissionError as e:
            errors.append(str(e))

    rows.sort(key=lambda r: r["auprc"], reverse=True)

    leaderboard_path.parent.mkdir(parents=True, exist_ok=True)
    leaderboard_path.write_text(_render_leaderboard(args.challenge, rows, len(errors)))
    print(f"Wrote {leaderboard_path} ({len(rows)} valid submission(s), {len(errors)} error(s))")

    if errors:
        print("\nValidation errors:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
